apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

commonLabels:
  app: securebooks
  managed-by: flux

commonAnnotations:
  description: "SecureBooks application - secure FastAPI + PostgreSQL deployment"

resources:
  - ../helm-release.yaml
  - ../secrets/external-secret.yaml
  - ../policies/calico/network-policy.yaml
  - ../istio/gateway.yaml
  - ../policies/kyverno/require-app-label.yaml
  - ../policies/kyverno/disallow-privileged.yaml
  - ../policies/kyverno/require-resource-limits.yaml
