apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

commonLabels:
  app: securebooks
  managed-by: flux

commonAnnotations:
  description: "SecureBooks application - secure FastAPI + PostgreSQL deployment"

resources: []
