apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: securebooks-dev

namespace: app

resources:
  - ../../clusters/dev/helm-release.yaml
  # - ../../secrets/external-secret.yaml  # Using manual Secret instead (ESO image pull issues)
  - ../../policies/calico/network-policy.yaml
  - ../../istio/gateway.yaml
  - ../../policies/kyverno/require-app-label.yaml
  - ../../policies/kyverno/disallow-privileged.yaml
  - ../../policies/kyverno/require-resource-limits.yaml

commonLabels:
  environment: dev
  version: v1

commonAnnotations:
  managed-by: flux
  environment: development
