apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: securebooks-dev

namespace: app

resources:
  - ../../clusters/dev/helm-release.yaml
  # - ../../secrets/external-secret.yaml  # Disabled: ESO image pull issues (requires private registry auth)
  - ../../policies/calico/network-policy.yaml
  # - ../../istio/gateway.yaml  # Disabled: Will enable after core app deployment
  # - ../../policies/kyverno/require-app-label.yaml  # Disabled: Kyverno pods can't pull images (needs private registry)
  # - ../../policies/kyverno/disallow-privileged.yaml  # Disabled: Kyverno pods can't pull images
  # - ../../policies/kyverno/require-resource-limits.yaml  # Disabled: Kyverno pods can't pull images

commonLabels:
  environment: dev
  version: v1

commonAnnotations:
  managed-by: flux
  environment: development
