apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: securebooks-staging

namespace: app

resources:
  - ../base

replicas:
  - name: securebooks
    count: 3

commonLabels:
  environment: staging
  version: v1

commonAnnotations:
  managed-by: flux
  environment: staging

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: securebooks
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 768Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 750m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 384Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 375m

patchesStrategicMerge:
  - deployment-patch.yaml
